# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, myapp1]

    strategy:
      matrix:
        node-version: [18.20.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: install server dependencies
      working-directory: .
      run: |
        npm install
        npm run build --if-present
    - name: install client dependencies
      working-directory: ./front
      run: |
        npm install
        npm run build --if-present
    - name: start application
      run: |
        pm2 start ecosystem.config.js
        pm2 save
